config/routes.rb
Rails.application.routes.draw do
  resources :users
  
  match '/signup', to: 'users#new', via: [:get, :post]

    # Static Page Routes
  match '/help',  to: 'static_pages#help', via: [:get, :post]
  match '/about',  to: 'static_pages#about', via: [:get, :post]
  match '/contact',  to: 'static_pages#contact', via: [:get, :post]

  root :to => 'static_pages#home'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# User mode for website users
class User < ApplicationRecord
  before_save { |user| user.email = user.email.downcase }
  has_secure_password

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # include SessionsHelper
end

app/controllers/static_pages_controller.rb
# Controller to handle static website pages.
class StaticPagesController < ApplicationController
  def home 
  end
  def help 
  end
  def about 
  end
  def contact 
  end
end

app/controllers/users_controller.rb
# User controller class for application users.
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # sign_in @user
      flash[:success] = 'Welcome to the Sample App!'
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
# Helpers needed throughout application
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = 'Ruby on Rails Tutorial Sample App'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
# Empty module for Static Pages
module StaticPagesHelper
end

app/helpers/users_helper.rb
# Module for showing gravatar images
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_alert_messages.html.erb
<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Design by: <a href="#">Patrick Scully</a>"
  </small>
  <nav>
    <ul>
      <li><%= link_to  "About", about_path %></li>
      <li><%= link_to  "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-expand-lg navbar-light bg-light">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to  "sample app", root_path, id: "logo", class: "navbar-brand" %>
      <nav>
        <ul class="nav justify-content-end nav-tabs">
          <li class="nav-item">
            <%= link_to  "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to  "Help", help_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to  "Sign In", '#', class: "nav-link" %>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <!-- [endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= render  "layouts/shim" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render  "layouts/header" %>
    <div class="container">
      <%= render 'layouts/alert_messages' %>
      <%= yield %>
      <%= render  "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-error">
            The form contains
            <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li>*
                    <%= msg %>
                </li>
                <% end %>
        </ul>
    </div>
    <% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us</h1>
<p>I am a Sample App</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact Us</h1>
<p>I am a Sample App</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help Page</h1>
<p>I am a Sample App</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>
  <p>This is the home page for the Ruby on Rails Tutorial Sample App.</p>
  <%= link_to  "Sign up now!", "/signup", class: "btn btn-large btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit "Create my account!", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>